services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\RuleEngine\StackRecommender:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\MarkdownGenerator\MarkdownGenerator: ~
